### ISSUE TITLE
Ability to add new monomers to existing graphical sequence

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#10]
As a user of the web application, I am able to drag and drop elements from the monomer palette onto the Canvas to add them to the current sequence or replace existing monomers, so that I can begin to modify the existing molecule.

Requirements:
  - The user can grab a monomer from the monomer palette and drop it on the canvas.
    - If dropped next to existing sequence, attempt to link this to current sequence (if there are possible attachment points).
    - If dropped on top of an existing element, replace that element.

**Comment by sabhilash** [comment]
Fixed by PR# 78
