### ISSUE TITLE
Alternate representations supported in Canvas

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#12]
As a user of the web application, I am able to retrieve alternate representations of the existing sequence, so that I can use the appropriate form for the external application I will use next.

Requirements:
  - The Canvas pane is able to render alternate sequence representation (i.e. PEPTIDE sequence, HELM, SMILES, Canonical HELM, image).
  - Dropdown added to the Canvas pane to allow user to select desired representation.
  - When new representation is selected, application makes a call to the HELM2WebService to retrieve the new representation.

**Comment by jsanford8** [comment]
We need to make sure that HELM and Canonical HELM are possible here.

**Comment by jsanford8** [comment]
A lot of this has been completed in #65.

Remaining work is image, if we want that to be loaded here. Not sure.

**Comment by sabhilash** [comment]
Lower pane will become crowded if we display the image there; also image might not be easily viewable there. I think, the image could be displayed in a popup, launched from the contextual menu entries #13

**Comment by jsanford8** [comment]
Sounds good to me. Should we close this issue the , and maybe make a new
one (that might not be for the final report) to expose the image generation
in a pop up?

**Comment by jsanford8** [comment]
Closing due to the alternate information being available in the lower pane
