### ISSUE TITLE
Recently used monomer list in monomer palette

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#16]
As a user of the web application, I can see monomers that I have recently used within the web application, so that I can easily find things that I use often.

Requirements:
  - There is a “recently-used” view in the monomer palette that is populated with the 20 most-recently-used monomers.
  - These recently-used monomers are remembered across user sessions on the same computer.

**Comment by jsanford8** [comment]
If this is easy to add, I think we can still plan on doing this work. However, @cokongwu , the view is already a bit complicated, and with the ability to search by monomer ID/name, I'm not sure this is totally needed. Up to you if you think you can implement this feature, but I think we should merge library back into master once you have a chance to review it and then we can build this feature out additionally afterwards.

Thoughts?

**Comment by cokongwu** [comment]
That sounds reasonable. My original attempt at this was just to create an
array of recent accessed monomers that is managed by the monomer library.
The last commit I made on thursday/friday had an implementation that we
could use. While I think that this should be ok for implementing the
back-end functionality to support this, I agree that it would probably add
clutter to the view. I think we should wait, and focus on the current stuff
now before trying to add additional functionality.

Chinedu

**Comment by jsanford8** [comment]
Sounds good to me. I'm going to issue a PR from library into master to get
that out there for others to see.

Thanks,
Justin

**Comment by jsanford8** [comment]
The current plan on this is to defer this feature until it is further understood. What does it mean to have been "used"? Is that only monomers that have been added to the canvas? Or ones that were searched for? Clicked? Double-clicked (i.e. to see the details)?

**Comment by cokongwu** [comment]
At the time we were first working on the library, I was not quite sure what
was intended, but the assumption I made was that we would add the most
recently searched monomers to the list of recent monomers. Using a
predefined maximumRecent number to maintain the list size, the plan was to
add the search result to the head of the list, trimming the end of the list
or possibly removing a duplicate recent selection if necessary. I thought
it was easiest if the list was updated and maintained by the action of
choosing a search result.

Chinedu

**Comment by jsanford8** [comment]
That's how I was leaning, too, but now that searching isn't "exact" (partial matches are returned), and there's no active "search" button, I don't know when we can tell if those are used often or not.

Also, I would propose we go back to the stakeholders and ask if this is necessary now that searching is possible - it's incredibly quick, so it's not like a lot of time would be saved with the recently used list.

**Comment by cokongwu** [comment]
I was under the impression that we had already decided not to add this feature because it would clutter the view and wasn't exactly needed. Despite that, I think it's a great suggestion to check with the stakeholders first rather than omit this feature on our own without their knowledge.

Chinedu

**Comment by jsanford8** [comment]
Closing for now, as the ability to search provides the functionality needed.
