### ISSUE TITLE
Monomer library view and modification

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#17]
Add a separate view to view and search within the existing monomer library (monomer manager)

  - This begins the work that would be needed to allow users to update the monomer library that is being used.
  - The display here is similar to what exists in the current HELM editor.
  - This must be a separate component.

**Comment by jsanford8** [comment]
@cokongwu I think we're leaving this one out, as this was a completely different view to enable people to edit the monomer library, which we're not doing. It's fine to add a new view to search through the monomer library, but this is different than the monomer library palette, which is on the main view and enables the user to click through all of the various elements.

**Comment by cokongwu** [comment]
Great, thanks for the heads up.

Chinedu

**Comment by jsanford8** [comment]
Initial work is done for searching, but no editing will be done for this project. Closing the issue
