### ISSUE TITLE
Support for HELM Antibody Editor

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#19]
Add support for HAbE (antibody editor) to the web application

**Comment by sabhilash** [comment]
Is this in our scope?

**Comment by jsanford8** [comment]
No, this is not planned for the final milestone of the class. It was put as
a placeholder in case we'd have extra time, but I do not think we'll get to
it. We can either close it, or keep it where it is (in a future milestone),
up to you guys.

Thanks,
Justin
