### ISSUE TITLE
HELM2WebService instance self-documentation does not work

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#2]
The hosted version of the HELM2WebService (http://104.236.250.11:8080/WebService/HowToUse.html) is supposed to include self-documentation through Swagger, but this is currently not working. All RESTful API endpoints do seem to work, though

**Comment by sabhilash** [comment]
This works in localhost. I have created a html file for documentation...we can refer that. Still not sure why its not working in the hosted version.

**Comment by jsanford8** [comment]
It has been decided this is not going to be fixed. Closing
