### ISSUE TITLE
Interfacing with HELM2Webservice

### ISSUE THREAD

**Issue by sabhilash** [CSCIE-599/HELM-Editor-UI#20]
Add functionality in HEML Editor AngularJS application to interface with the HELM2Websphere.

The web service exposes a RESTful API and has the following functionalities:
● conversion from Peptide or RNA String sequences into HELM notation,
● conversion from HELM notation into canonical HELM notation,
● conversion from HELM notation into JSON output,
● conversion between HELM notation and Fasta Sequences, and
● generation of image representations of monomer and HELM molecules.

This task is to identify the interfacing/communication logic to invoke the appropriate API.

**Comment by sabhilash** [comment]
Prototype is available in branch:
https://github.com/CSCIE-599/HELM-Editor-UI/tree/20-webservice-interface 

Added a simple DIV in Main.html, and a controller to main.js file - with which we can input a RNA/PEPTIDE sequence and generate a HELM notation and output it to Main.html.

**Comment by sabhilash** [comment]
Added a factory for webservice functionality in main.js

**Comment by sabhilash** [comment]
Added unit test cases and all APIs

**Comment by jsanford8** [comment]
Reopening until the unit tests are fixed

**Comment by sabhilash** [comment]
Integrated to master
