### ISSUE TITLE
Canvas Pane can display graphical representation of HELM string

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#5]
As a user of the application, I am able to see the correct graphical representation of a given HELM sequence within the Canvas pane within the web application so that I can begin visualizing the molecule.

Requirements:
  - Canvas pane can render the graphical representation of a HELM sequence.
  - Only the representation of the HELM sequence in graphical view is included (i.e. does not include adding, removing, moving, or replacing elements).
  - Only one sequence needs to be supported initially.
  - Canvas pane is added to the web application display.

**Comment by thankam** [comment]
Basic functionality for adding a single node sequence is,  by the click of a button is checked in.

All the code is in the branch: https://github.com/CSCIE-599/HELM-Editor-UI/tree/5-canvas-display

It needs to be extended to accept a text input from the modal and of course handle multi nodes.
(This might overlap with issue#6 and may be others too)

Following are some immediate next steps, in the order of priority:

1. Add unit tests
2. Have the sequence appear in the middle of the canvas, like in the swing editor, currently it just appears at a hard-coded coordinate.
3. Extend it to draw multi-node sequence (This will be huge)
4. Selecting/dragging nodes on the canvas(theres some code for this, which is not used currently)
5. Finally dragging and attaching to other sequences/nodes.

**Comment by SarahL88** [comment]
Wow, Thankam - you've done a lot - looks great!
I'll try to take on the To-Do items you listed below and get back to you soon with a status update.
Sarah

**Comment by jsanford8** [comment]
Agreed, Thankam, this looks great! I haven't had a chance to really dig
into what you've done here, but there looks to be a whole lot that you've
put in here.

I know we're still in the prototyping phase, so some of this clearly
doesn't apply yet, but I wanted to get this out there so that people can
start adopting a structure that will help future people enhance this
project once we're done. I'm going to send out a separate email to detail
this, but I think we really should adopt a standard layout and file
structure so that we can all work on the same page, and people can adopt
this later. See my other email about this.

Thanks,
Justin

**Comment by SarahL88** [comment]
I finally wrapped my head around Angular and Thankam's branch enough to make an edit.
I want to make sure that my git process was correct.
1) Justin, you said to use 'git push -r origin <branch>' in your earlier e-mail.   I got the error 'unknown switch `r' so I just used "git push origin 5-canvas-display' (without the '-r').  Is it ok going forward not to use '-r', or is that important?
2) Also, I did not make a pull request.  Should I do this?  Or do we wait until the branch is more fully vetted/tested to do this?
Also, Thankam, let me know if you want to take on anything in particular from the To-Do list below going forward, so we don't accidentally work on the same thing in parallel.  
Thanks,Sarah

**Comment by jsanford8** [comment]
Sorry, Sarah, that was supposed to be -u (for "upstream"). I think it works
without the -u, but I always include it just in case (sometimes it doesn't
work depending on how your origin/branch/fork is set up.

As for PRs, those should be when you're ready to push what you have to main
(which typically would be when a feature is complete and/or there are unit
tests complete etc. it's kind of vague on purpose). That said, you can pull
everything from main into your branch (which you should do often to
minimize painful merges), so in that way you can pull, for instance, the
web service that has been created so far (and use that where you need to).

-Justin

**Comment by tgirija** [comment]
Sarah, That to-do list has changed a bit but unit testing still remains the top priority. I had pushed some changes to it last night and I'm continuing to work  on developing the sequence. If it's helpful we can do a quick code walkthrough. Let me know.

**Comment by SarahL88** [comment]
Thankam, I'm happy to work on unit testing.  
I think I'd benefit from talking about this first.  I'm not familiar with how karma and jshint.  I'm happy to research that on-line, but I think it would be helpful to discuss it, and also just check-in to see what you need in general.
Are you available anytime tonight by any chance?  I can do anytime tonight.
Sarah

**Comment by jsanford8** [comment]
I'm also happy to walk you through Karma/jshint if you want.

Thanks,
Justin

**Comment by SarahL88** [comment]
Great - can you do tonight - what time is best for you?
Sarah

**Comment by jsanford8** [comment]
Ideally it would be sometime between 7 and 8:30 eastern, if that works for
you.

-Justin

**Comment by SarahL88** [comment]
I could do anytime in that range - earlier would be great.  Is 7pm eastern too soon for you?  That is ten minutes from now.
Sarah

**Comment by tgirija** [comment]
Sarah, I can meet around 9.30pm(EST) tonight. Is it too late for you? I'm
not familiar with Karma and Jshint either, which is why I held back on
adding unit tests so far. Justin might be able to help with that. But, I
can talk about the functionalities thats been added for the canvas display
so far, that need to be unit tested. Does that work?



Thanks,

Thankam Girija
(443) 980 6737

**Comment by tgirija** [comment]
Oh sorry, missed the 2 emails in between, I can shoot for 8.30p.m as well.

Thanks,

Thankam Girija
(443) 980 6737

**Comment by sabhilash** [comment]
I am ok with 8.30pm tonight.

**Comment by jsanford8** [comment]
Okay, can the four of us (and Chinedu/Stephanie if that's not too late
notice) meet at 8:30 eastern, and I'll go over the folder structure, Karma,
jshint, etc?

Thanks,
Justin

**Comment by thankam** [comment]
Sarah, I updated the canvas branch with the new directory structure we discussed, along with the following changes:
1. updated index.html with the new paths
2. removed dependency from dragging service and mouse_capture services, although files are moved into a separate service directory(need to see if it should go into factory instead)
3. removed all code related to mouse events throughout
4. added model(for helm_viewmodel.js) directory and common(svg_class.js) directories
5. As for the tests, there was already main.js under test/specs/controllers, so you can start there. Most of our helm related changes are in main.js, so good place to start. Also added an empty .js file for helm_modelview.js under test/specs/model
6. I pulled your connection change and tested it, looks great.
7. I'll start looking at the Hexagon shape support next...every other shape can be supported with the current directive/template that we have.
8. Other upcoming tasks in terms of functionality:(I'll try to add tasks in git for these)
- Scaling the nodes/connections based on canvas size
- Clearing the canvas on loading a new sequence
- Adding the sequence in the middle of the canvas like the current editor does
- Validating an input sequence

**Comment by jsanford8** [comment]
Hi Thankam,

I was actually able to get it set up within the helmeditor2App module, so
I'm going to go ahead and check this in to the branch (we can always revert
the commit if we need to). One thing that you'll notice is that I moved the
directive into a file called /app/scripts/directives/helmcanvas.js, and all
of the factories/services should be be moved into new files under
app/scripts/services, with names that don't really need "Service" in them
if it's not necessary (such as dragging could just be dragging). This will
then allow us to create the similarly named js files under
/test/spec/services that we can then use to unit test the
Services/Factories as necessary.

We're making some great progress here, thanks for all of the work you've
done!

-Justin

**Comment by jsanford8** [comment]
Also, a couple of other notes here:

   - helmnotation (helm_viewmodel.js) I think really belongs within an
   angular factory or service, or even directly within the controller that
   uses it... in theory, we should be getting rid of globals as much as we
   possibly can. We can refactor this later if needed.
   - when we want to use dragging or mouseCapture, we should create proper
   service for them (and make sure we cite where we got the starter from)
   - I haven't quite yet got the hang of everything that's going on - is
   this taking a peptide sequence directly and displaying it? What this really
   should be doing is taking a HELM string and displaying it correctly, and
   the other issue (6) is responsible for taking a peptide or nucleotide (or
   any other sequence) and converting it to HELM notation. The input of this
   canvas should be a HELM notation, but I *think* right now it's a peptide
   sequence.

-Justin

**Comment by jsanford8** [comment]
Sorry, last email for now, I promise - one of the side effects of having
helm_viewmodel outside of the scope of the Angular controller (or a service
that we can inject into the test harness) is that we cannot test the
controller right now. Either we need to update the test with a dummy
helmnotation object (which may be the way to go anyway), or we need to
figure some other way around having this as a global.

-Justin

**Comment by sabhilash** [comment]
To clarify the usecases/ subtsaks:

This usecase handles the **graphical display** of a Peptide, Nucleotide, or Chemical Modifier in the Canvas. Input to this service/implementation will be a sequence of one of these three types.

This service will be invoked/utilized from 2 places/components.
1. Dragging and dropping from Monomer palette (for Milestone3)
2. From Load Sequence Modal - Usecase#6 - This usecase will have to display a modal dialog. In that modal dialog, users can input either a Peptide/Nucleotide sequence or a HELM notation string. 
2.1. Input Peptide/Nucleotide sequence (Milestone2) - Modal dialog should invoke the canvas graphical display service to display the graphic for the sequence in the canvas.
2.2. Input HELM notation string (Milestone3) - Modal dialog should parse the HELM string to get the corresponding Peptide or Nucleotide sequence. (it might also have to invoke the WebServices API to get the JSON representation of the HELM string for parsing). Once the corresponding Peptide or Nucleotide sequence is identified, modal dialog should invoke the canvas graphical display service to display the graphics corresponding the Peptide/Nucleotide sequence.

**Comment by jsanford8** [comment]
Hi everyone,

That's actually not how I intended the use cases, and potentially why there
is some confusion about where 5 ends and 6 starts.

Simili, you're right: 5 (this one) is about the GRAPHICAL display only, but
it's not the direct display of a Peptide, Nucleotide, or Chemical modifier
string. Instead, this is about the GRAPHICAL display of a HELM NOTATION
STRING (sorry, on my phone, can't use bold so I'm going with CAPS). So, for
this first use case, and what we're aiming for for milestone 2, the input
to this component (interface) is a HELM string, and this component needs to
graphically display this in the canvas. It should not be taking a Peptide
or Nucleotide string (like ATG) and displaying it directly, or we risk
overlapping the functionality already existing in the HELM2WebSsrvice.

I realize this prototype was written to take a peptide/nucleotide sequence
directly, and that's why the UI exists as it is and why there's an
if(peptide) {...} else {...} branch in the code, but we should not be doing
this. Instead, the canvas should have a method like convertHelmToGraph()
that takes a full HELM notation and displays it.

Then we have use case 6, which is what handles taking the
peptide/nucleotide sequence from the user, calling out to the web service
to convert it to HELM, and passing the resulting HELM string to the canvas
to display it.

This brings up a breakdown of work that I don't think was apparent
previously. For instance, Thankam can continue to work on the display of
nodes, and Sarah could work on converting a HELM string into the
appropriate node/edge chart. Then Stephanie works on the UI taking in
nucleotide, peptide, and HELM notation, converts nucleotide and peptide to
HELM, validates the HELM (both through the web service), and passes this on
to the canvas to display it.

Does that make sense? I can try to write this out more fully, but it seems
this was a point of confusion before.

Justin

**Comment by sabhilash** [comment]
Note that - The HELM2Webservice returns only the "atomic structure" image (see image below), not the "graphical image".

![image](https://cloud.githubusercontent.com/assets/4276581/13817003/e2282b40-eb66-11e5-8425-3c577df5a8dd.png)

HELM2Webservice does provide the graphical image for a Peptide/RNA/ or HELM sequence. So, usecase#6 will have to "build" the graphical image for the underlying peptide/nucleotide sequence. Usecase#6 provides option to input a peptide/RNA sequence as well as HELM sequence. We have to show the graphical image even for peptide/RNA in canvas, right?

For identifying the underlying peptide/nucleotide sequence of a HELMNotation - we can utilize the WS API that return a JSON string corresponding to a HELM string. 

Parsing this JSON string and identifying the base sequence will be a huge/independent task.

For e.g., as shown in the image... The HELM notation corresponding to the PEPTIDE sequence AA is PEPTIDE1{A.A}$$$$V2.0. If we input this HELM sequence in UI, the app should be able to display the "graphical image" corresponding to AA in canvas. 

If we provide this helm string to the HELM2Webservice JSON API, it provides the below JSON string back. We need to parse it to identify the underlying peptide/nucleotide sequence (AA in this case).

{
  "JSON": "{\n  \"listOfPolymers\" : [ {\n    \"polymerID\" : {\n      \"id\" : \"PEPTIDE1\",\n      \"type\" : \"PEPTIDE\"\n    },\n    \"annotation\" : null,\n    \"polymerElements\" : {\n      \"listMonomerNotations\" : [ {\n        \"annotation\" : null,\n        \"count\" : \"1\",\n        \"type\" : \"PEPTIDE\",\n        \"id\" : \"A\"\n      }, {\n        \"annotation\" : null,\n        \"count\" : \"1\",\n        \"type\" : \"PEPTIDE\",\n        \"id\" : \"A\"\n      } ],\n      \"listOfElements\" : [ {\n        \"annotation\" : null,\n        \"count\" : \"1\",\n        \"type\" : \"PEPTIDE\",\n        \"id\" : \"A\"\n      }, {\n        \"annotation\" : null,\n        \"count\" : \"1\",\n        \"type\" : \"PEPTIDE\",\n        \"id\" : \"A\"\n      } ]\n    }\n  } ],\n  \"listOfConnections\" : [ ],\n  \"listOfGroupings\" : [ ],\n  \"listOfAnnotations\" : [ ]\n}",
  "HELMNotation": "PEPTIDE1{A.A}$$$$V2.0"
}

We can discuss more in tomorrows call.

**Comment by SarahL88** [comment]
I don't totally get what Justin laid out in the e-mail below - specifically the second to last paragraph.
Here is my interpretation of how to separate work between Thankam, Stephanie, and me.
I'm looking at the first wireframe at https://drive.google.com/file/d/0BzWuaNlFrlmkaEQ1cFpCYjRhMnhXdzRndFdZbTJ6MkR0dlFN/view.
1) Stephanie takes 'ACGU' from user input and turns it into RNA1{R(A)P.R(C)P.R(G)P.R(U)}$$$$2) I take RNA1{R(A)P.R(C)P.R(G)P.R(U)}$$$$ and translates that to arrays of (R, A, P, R, C, P, R, G, P, R, U) nodes and edges3) Thankam takes arrays of  (R, A, P, R, C, P, R, G, P, R, U) nodes and edges  and makes a graph
Pretty sure this is wrong.  Let me know so I can work on stuff today. Sounds like I should hold off on making the unit tests?
Thanks,Sarah

**Comment by SarahL88** [comment]
So, should I continue to work on unit tests for the 5-canvas-display branch?  
Or will that branch change so much, that I should hold off?
Sarah

**Comment by jsanford8** [comment]
I'm going to take this out of Github replies to make sure everyone's
getting it... one sec.

-Justin

**Comment by jsanford8** [comment]
Closing this, as this user story is complete. Additional work will continue in the next milestone
