### ISSUE TITLE
Create checkbox when loading new sequence to clear current canvas

### ISSUE THREAD

**Issue by jsanford8** [CSCIE-599/HELM-Editor-UI#52]
Create checkbox when loading new sequence to clear current canvas

**Comment by sabhilash** [comment]
We do not support loading multiple sequences into the canvas pane as of now. So, the canvas pane has to be cleared before each load, regardless of whether a check box is selected or not.  Also, we already have s reset button that enables the manual clearing. So, do we need to add such a checkbox?

**Comment by jsanford8** [comment]
That was my thinking, as well, and why I had put something in to always
clear the canvas when you enter a new sequence. That said, I guess it
doesn't really hurt, and it brings it in line with the current editor (and
will be used at the point where, in the future, the editor does support
loading additional sequences).

**Comment by sabhilash** [comment]
Added the reset check box. Kept it as checked and disabled. Removed the "Reset Button".
